


# BEGIN_KITTY_FONTS
font_family      family="JetBrainsMonoNL Nerd Font Mono"
bold_font        family='JetBrainsMonoNL Nerd Font Mono' style=ExtraBold
italic_font      family='JetBrainsMonoNL Nerd Font Mono' style='Light Italic'
bold_italic_font family='JetBrainsMonoNL Nerd Font Mono' style='ExtraBold Italic'
font_size 8.0
# END_KITTY_FONTS

# BACKGROUND
background_opacity 0.0
dynamic_background_opacity yes

# CURSOR
cursor_shape                 beam
cursor_beam_thickness        1.8
cursor_blink_interval        0.5
cursor_stop_blinking_after   0
cursor_trail                 3
cursor_trail_decay           0.1 0.4
cursor_trail_start_threshold 2



# BEGIN_KITTY_THEME
# Cyberpunk
include current-theme.conf
# END_KITTY_THEME
