
general {
    disable_loading_bar = true
    hide_cursor = true
}

background {
    path = screenshot
    color = rgba(25, 20, 20, 0.2) 
    vibrancy_darkness = 0.0
    brightness = 0.81
    vibrancy = 0.1696
    contrast = 0.89           
    blur_passes = 4           
    noise = 0.0117
    blur_size = 7             
    monitor =
}

label {
    font_family = JetBrainsMono Nerd Font
    color = rgba(255,255,255,0.9)
    position = 0, 300
    font_size = 90
    halign = center
    valign = center
    text = $TIME
    monitor =
}

label {
    text = cmd[update:1000] echo "$USER"
    font_family = JetBrainsMono Nerd Font
    color = rgba(255,255,255,0.6)
    position = 0, 150
    font_size = 25
    halign = center
    valign = center
    monitor =
}

input-field {
    outer_color = rgba(255,255,255,0.2)
    inner_color = rgba(255,255,255,0.1)
    font_color = rgba(255,255,255,1.0)
    placeholder_text = Password...
    outline_thickness = 2
    fade_on_empty = false
    dots_spacing = 0.2
    dots_center = true
    hide_input = false
    position = 0, -50
    halign = center
    valign = center
    dots_size = 0.3
    size = 300, 60
    rounding = 12
    monitor =
}

