general {
    lock_cmd = pidof hyprlock || hyprlock       # dbus/sysd lock command (loginctl lock-session)
    before_sleep_cmd = loginctl lock-session    # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on  # to avoid stuck black screen after resume
}

# THE LID LOGIC
listener {
    event = sw_on:Lid Status
    on-status-changed = bash -c 'if [[ $(hyprctl monitors -j | jq "length") -gt 1 ]]; then hyprctl keyword monitor "eDP-1, disable"; else systemctl suspend; fi'
}

listener {
    event = sw_off:Lid Status
    on-status-changed = hyprctl keyword monitor "eDP-1, preferred, auto, 1"
}

# (Optional) Standard idle timeout
listener {
    timeout = 300                                # 5 mins
    on-timeout = loginctl lock-session           # lock screen
}
