add_newline = true
command_timeout = 200
format = " [$directory$git_branch$git_status]($style)($python) $character "

[character]
error_symbol = "[!!](bold #FF0000)"
success_symbol = '[\$](bold #00FF00)'

[directory]
style = '#CFCFCF'
truncation_length = 2
truncation_symbol = "⟡ "
repo_root_style = "#00FF00"
repo_root_format = "[$repo_root]($repo_root_style)[$path]($style)[$read_only]($read_only_style)"

[python]
format = '[(${virtualenv})]($italic #808080)'

[git_branch]
format = " \\[$branch\\]($style) "
style = "italic #FFFF00"

[git_status]
format     = '[$all_status]($style)'
style      = "#FFFF00"
ahead      = "⇡${count} "
diverged   = "⇕⇡${ahead_count}⇣${behind_count} "
behind     = "⇣${count} "
conflicted = " "
up_to_date = " "
untracked  = "? "
modified   = " "
stashed    = ""
staged     = ""
renamed    = ""
deleted    = ""
